server:
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /

spring:
  application:
    name: lc后台管理
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 项目相关配置
lc:
  # 名称
  name: LangChao
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /Users/yanglinkai/IdeaProjects/lc-vue/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: joeabcdlmuopvwxthijkzefgnyqrs
  # 令牌有效期（默认30分钟）
  expireTime: 300

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ylkget.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Swagger配置
swagger:
  # 是否开启swagger
  enable: true
  # 请求前缀
  application-name: ${spring.application.name}
  application-version: 1.0.0
  application-description: springfox swagger 3.0整合 lc
  # 请求前缀
  path-mapping: /dev-api

# 日志配置
logging:
  level:
    com.ylkget: debug
    org.springframework: warn
    org:
      mybatis:
        spring:
          mapper: debug